name: Publish JouleHunter to PyPI and TestPyPI

on:
    push:
        branches: [main]
        tags: -v*

jobs:
    build_sdist:
        name: Build source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              name: Install Python
              with:
                  python-version: "3.8"

            - name: Build sdist
              run: python setup.py sdist

            - uses: actions/upload-artifact@v2
              with:
                  path: dist/*.tar.gz
    publish:
        name: Build and publish Publish JouleHunter to PyPI and TestPyPI
        runs-on: ubuntu-latest
        needs: [build_sdist]
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: artifact
                  path: dist

            - name: Publish distribution 📦 to Test PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                  password: ${{ secrets.TEST_PYPI_API_TOKEN }}
                  repository_url: https://test.pypi.org/legacy/

            - name: Publish distribution 📦 to PyPI
              if: startsWith(github.ref, 'refs/tags')
              uses: pypa/gh-action-pypi-publish@master
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
